### ISSUE TITLE
Issue Compiling Sources

### ISSUE THREAD

**Issue by iancornelius** [sonyxperiadev/device-sony-pdx206#7] opened 2021-04-30 08:42 UTC
```
vendor/qcom/opensource/media/sm8250/mm-video-v4l2/vidc/venc/src/video_encoder_
device_v4l2.cpp:4504:28: error: no member named 'flags' in 'CVPMetadata'
    } else if (cvpMetadata.flags & CVP_METADATA_FLAG_REPEAT) {
               ~~~~~~~~~~~ ^
vendor/qcom/opensource/media/sm8250/mm-video-v4l2/vidc/venc/src/video_encoder_
device_v4l2.cpp:4504:36: error: use of undeclared identifier 'CVP_METADATA_FLA
G_REPEAT'
    } else if (cvpMetadata.flags & CVP_METADATA_FLAG_REPEAT) {
                                   ^
2 errors generated.
```

Only occurs when compiling for pdx206

```

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=11
TARGET_PRODUCT=aosp_xqas52
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-2a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-2a
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.11.0-16-generic-x86_64-Ubuntu-21.04
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=RQ2A.210305.006
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/sony/common device/sony/edo vendor/qcom/opensour
ce/core-utils
============================================
```

**Comment by MarijnS95** [comment] 2021-04-30 08:43
Duplicate of #6.

**Closed as completed** 2021-04-30 08:43 UTC
